# Generated by Django 3.0.3 on 2020-03-30 04:42

import apps.venta.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('DUI', models.CharField(blank=True, help_text='formato: 00000000-0', max_length=10, null=True, validators=[apps.venta.models.ValidarDUI])),
                ('NIT', models.CharField(blank=True, help_text='formato: 0000-000000-000-0', max_length=20, null=True, validators=[apps.venta.models.ValidarNIT])),
                ('NRC', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, help_text='fomato: 0000-0000', max_length=9, null=True, validators=[apps.venta.models.ValidarTelefono])),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=datetime.datetime(2020, 3, 29, 22, 42, 27, 533797))),
                ('estado', models.BooleanField()),
                ('total_venta', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='venta.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Inventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venta.Venta')),
            ],
        ),
    ]
